name: support_panel
description: "SuperCyp Müşteri Temsilcisi Paneli"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  data_table_2: ^2.5.15
  fl_chart: ^0.70.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # Supabase
  supabase_flutter: ^2.9.0

  # File Picker
  file_picker: ^8.1.6

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
